worker_processes auto;
pid /tmp/nginx.pid;
error_log /dev/stderr crit;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  server_tokens off;
  sendfile on;
  gzip on;
  gzip_vary on;
  gzip_min_length 256;
  gzip_types text/plain text/css text/xml application/xml application/json application/javascript application/manifest+json image/svg+xml;
  charset utf-8;
  charset_types text/plain text/xml application/xml text/css application/javascript application/json;
  include /etc/nginx/conf.d/*.conf;
}
