import { format, resolveConfig } from 'prettier'

import type { Manifest } from '../../packages/animated-fluent-emojis/src/utils/types.js'
import { listRegistryKeys, type SlugRegistry } from './public-slugs.js'

/**
 * Builds the file name of a category's emoji list.
 * @param categoryTitle The category title, such as `Travel and places`.
 * @returns A name like `EMOJI_LIST_Travel_and_places.md`.
 */
export function buildCategoryFileName(categoryTitle: string): string {
  return `EMOJI_LIST_${categoryTitle.replaceAll(' ', '_')}.md`
}

function escapeCell(text: string): string {
  return text
    .replaceAll('|', String.raw`\|`)
    .replaceAll(/\s+/g, ' ')
    .trim()
}

function requireSlug(slugs: SlugRegistry, key: string): string {
  const slug = slugs.slugs[key]
  if (slug === undefined) throw new Error(`No public slug for ${key}.`)
  return slug
}

const FORMAT_LABELS = { gif: 'GIF', webp: 'WebP', png: 'PNG' } as const

function renderFileLinks(filesBaseUrl: string, slug: string): string {
  return Object.entries(FORMAT_LABELS)
    .map(
      ([format, label]) =>
        `[${label}](${filesBaseUrl}/${format}/${slug}.${format})`,
    )
    .join(' ')
}

/**
 * Renders the per-category Markdown emoji lists for a manifest. The hand-written
 * `EMOJI_LIST.md` index is left untouched. Each row gets a 32px PNG preview and
 * links to the GIF, WebP and PNG files; emoji with skin tones list the links of
 * every tone on their own line.
 * @param manifest The final emoji manifest.
 * @param slugs The frozen registry the file URLs are built from.
 * @param filesBaseUrl The files site origin, with or without a trailing slash.
 * @returns File contents keyed by file name, unformatted.
 * @throws {Error} When an emoji or tone has no slug in the registry.
 */
export function renderEmojiLists(
  manifest: Manifest,
  slugs: SlugRegistry,
  filesBaseUrl: string,
): Map<string, string> {
  const baseUrl = filesBaseUrl.replace(/\/+$/, '')
  const keysById = Map.groupBy(listRegistryKeys(manifest), ({ id }) => id)
  const files = new Map<string, string>()
  for (const category of manifest.categories) {
    const rows = category.emoticons.map((emoticon) => {
      const [defaultKey, ...toneKeys] = keysById.get(emoticon.id) ?? []
      const slug = requireSlug(slugs, defaultKey?.key ?? emoticon.id)
      const links = [
        renderFileLinks(baseUrl, slug),
        ...toneKeys.map(
          ({ key, tone }) =>
            `${tone.slice(1)}: ${renderFileLinks(baseUrl, requireSlug(slugs, key))}`,
        ),
      ].join('<br>')
      const preview = `<img src="${baseUrl}/png/${slug}.png" width="32" height="32" alt="">`
      return `| ${escapeCell(emoticon.id)} | ${preview} | ${emoticon.unicode} | ${escapeCell(emoticon.description)} | ${escapeCell([...new Set(emoticon.keywords)].join(', '))} | ${links} |`
    })
    files.set(
      buildCategoryFileName(category.title),
      [
        `# ${category.title}`,
        '',
        '| ID | Preview | Unicode | Description | Keywords | Files |',
        '| -- | ------- | ------- | ----------- | -------- | ----- |',
        ...rows,
        '',
      ].join('\n'),
    )
  }

  return files
}

function toLiteral(emoticon: { id: string }): string {
  return `  | ${JSON.stringify(emoticon.id)}`
}

/**
 * Renders the generated id module: the `EmojiId` union with one string
 * literal per catalog id in manifest order, and the `DiverseEmojiId` union
 * with the ids whose manifest `diverse` flag is set.
 * @param manifest The final emoji manifest.
 * @returns TypeScript source, unformatted.
 */
export function renderEmojiIdModule(manifest: Manifest): string {
  const emoticons = manifest.categories.flatMap(
    (category) => category.emoticons,
  )
  const diverseLiterals = emoticons
    .filter((emoticon) => emoticon.diverse)
    .map((emoticon) => toLiteral(emoticon))
  return [
    '/**',
    ' * Every emoji id in the published catalog. Generated by `bun run assets:lists`;',
    ' * do not edit by hand.',
    ' */',
    'export type EmojiId =',
    ...emoticons.map((emoticon) => toLiteral(emoticon)),
    '',
    '/**',
    ' * Every emoji id that has skin tone variants. Generated by `bun run assets:lists`;',
    ' * do not edit by hand.',
    ' */',
    diverseLiterals.length > 0
      ? 'export type DiverseEmojiId ='
      : 'export type DiverseEmojiId = never',
    ...diverseLiterals,
    '',
  ].join('\n')
}

/**
 * Formats source with the repository's Prettier configuration.
 * @param source The source text.
 * @param filePath A path used to resolve the Prettier config.
 * @returns The formatted source.
 */
export async function formatSource(
  source: string,
  filePath: string,
): Promise<string> {
  const options = await resolveConfig(filePath)
  return format(source, { ...options, filepath: filePath })
}
