import { format, resolveConfig } from 'prettier'

import type { Manifest } from '../../src/utils/types.js'

/**
 * Builds the file name of a category's emoji list.
 * @param categoryTitle The category title, such as `Travel and places`.
 * @returns A name like `EMOJI_LIST_Travel_and_places.md`.
 */
export function buildCategoryFileName(categoryTitle: string): string {
  return `EMOJI_LIST_${categoryTitle.replaceAll(' ', '_')}.md`
}

function escapeCell(text: string): string {
  return text
    .replaceAll('|', String.raw`\|`)
    .replaceAll(/\s+/g, ' ')
    .trim()
}

/**
 * Renders the per-category Markdown emoji lists for a manifest. The hand-written
 * `EMOJI_LIST.md` index is left untouched.
 * @param manifest The final emoji manifest.
 * @returns File contents keyed by file name, unformatted.
 */
export function renderEmojiLists(manifest: Manifest): Map<string, string> {
  const files = new Map<string, string>()
  for (const category of manifest.categories) {
    const rows = category.emoticons.map(
      (emoticon) =>
        `| ${escapeCell(emoticon.id)} | ${emoticon.unicode} | ${escapeCell(emoticon.description)} | ${escapeCell([...new Set(emoticon.keywords)].join(', '))} |`,
    )
    files.set(
      buildCategoryFileName(category.title),
      [
        `# ${category.title}`,
        '',
        '| ID | Unicode | Description | Keywords |',
        '| -- | ------- | ----------- | -------- |',
        ...rows,
        '',
      ].join('\n'),
    )
  }

  return files
}

/**
 * Renders the generated `EmojiId` union module, one string literal per
 * catalog id, in manifest order.
 * @param manifest The final emoji manifest.
 * @returns TypeScript source, unformatted.
 */
export function renderEmojiIdModule(manifest: Manifest): string {
  const literals = manifest.categories.flatMap((category) =>
    category.emoticons.map((emoticon) => `  | ${JSON.stringify(emoticon.id)}`),
  )
  return [
    '/**',
    ' * Every emoji id in the published catalog. Generated by `bun run assets:lists`;',
    ' * do not edit by hand.',
    ' */',
    'export type EmojiId =',
    ...literals,
    '',
  ].join('\n')
}

/**
 * Formats source with the repository's Prettier configuration.
 * @param source The source text.
 * @param filePath A path used to resolve the Prettier config.
 * @returns The formatted source.
 */
export async function formatSource(
  source: string,
  filePath: string,
): Promise<string> {
  const options = await resolveConfig(filePath)
  return format(source, { ...options, filepath: filePath })
}
